export const EXTRA_TECH_SKILLS: Record<string, string[]> = {
  "تقنية المعلومات": [
    "HTML",
    "CSS",
    "SASS",
    "Bootstrap",
    "REST APIs",
    "GraphQL",
    "Next.js",
    "Nuxt.js",
    "Express.js",
    "FastAPI",
    "Flask",
    "ASP.NET Core",
    "MongoDB",
    "PostgreSQL",
    "Redis",
    "RabbitMQ",
    "gRPC",
    "WebSockets",
    "Microservices",
    "CI/CD",
    "Jenkins",
    "GitHub Actions",
    "Vercel",
    "Netlify",
    "Heroku",
    "DigitalOcean",
    "Terraform",
    "Ansible",
    "Prometheus",
    "Grafana"
  ],
  "علوم البيانات": [
    "Python",
    "R",
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "Scikit-learn",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "XGBoost",
    "LightGBM",
    "SQL",
    "Spark",
    "Airflow",
    "Jupyter",
    "Tableau",
    "Power BI",
    "Docker",
    "MLflow"
  ],
  "أمن المعلومات": [
    "Penetration Testing",
    "OWASP Top 10",
    "Burp Suite",
    "Metasploit",
    "Wireshark",
    "Nmap",
    "Kali Linux",
    "Snort",
    "SIEM",
    "IDS/IPS",
    "Malware Analysis",
    "Reverse Engineering",
    "ISO 27001",
    "SOC",
    "Firewall",
    "Splunk"
  ],
  "DevOps": [
    "Linux Administration",
    "Docker",
    "Kubernetes",
    "Helm",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitLab CI",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "AWS",
    "Azure",
    "GCP",
    "Argo CD",
    "Istio",
    "GitOps",
    "Packer"
  ],
  "الصحة والطب": [
    "EMR",
    "EHR Systems",
    "PACS",
    "ICD-10 Coding",
    "HL7",
    "DICOM",
    "Radiology Information System",
    "Lab Information System",
    "Telemedicine Platforms",
    "Ventilator Operation",
    "Ultrasound",
    "X-Ray",
    "MRI",
    "CT Scan",
    "Surgical Robotics",
    "Medical Device Calibration",
    "Pharmacy Information System"
  ],
  "ذكاء اصطناعي": [
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "Computer Vision",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "OpenCV",
    "HuggingFace Transformers",
    "GPT",
    "Reinforcement Learning",
    "GANs",
    "Scikit-learn"
  ],
  "شبكات": [
    "CCNA",
    "CCNP",
    "Routing",
    "Switching",
    "BGP",
    "OSPF",
    "MPLS",
    "SDN",
    "Network Security",
    "Load Balancing",
    "Firewalls",
    "VPN",
    "Wireless",
    "IPv6",
    "QoS"
  ],
  "تطوير تطبيقات الجوال": [
    "Swift",
    "Objective-C",
    "Kotlin",
    "Java",
    "Flutter",
    "Dart",
    "React Native",
    "Ionic",
    "Android SDK",
    "iOS SDK",
    "Firebase",
    "Realm",
    "GraphQL",
    "UX/UI Mobile"
  ]
};
